#!/bin/bash

# fd to open the fzf for directories only. After selecting any directory change
# current directory to that location
# From https://github.com/junegunn/fzf/wiki/examples

fd() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}

fd
